### ISSUE TITLE
Get delta of GitHub notifications

### ISSUE THREAD

**Issue by stephenmichaelf** [karelz/GitHubIssues#162]
Give me delta for last x minutes - to compensate for missing notifications from "WebHook".

This should query periodically, get the recent items, then if anything is missing from our Issues data store, write it there.

**Comment by karelz** [comment]
Note: If there were multiple notifications for an issue, we might have missed one in the middle, not the latest.

When we identify issues with missing notifications, we can pull their [Timeline](https://developer.github.com/v3/issues/timeline/) to get the notification.

**Comment by karelz** [comment]
We should look into [GraphQL](https://developer.github.com/early-access/graphql/) if it can be used to query the delta for "last x minutes".
