### ISSUE TITLE
Weekly digest of not responded Closed-issues

### ISSUE THREAD

**Issue by karelz** [karelz/GitHubIssues#20]
The weekly digest (#4) would ideally cover also closed issues.

We need to find a way how to query only closed issues which have been commented in last X days.

**Comment by khellang** [comment]
You could just use search. I'm not sure if you can filter by date, but you could do `org:dotnet is:issue is:closed`, order it by most recently commented and just loop over the results until you get to the defined threshold.

**Comment by khellang** [comment]
Ok, looks like you can include an updated filter as well; `updated:>2017-03-02`

**Comment by karelz** [comment]
Thanks, I remember seeing some kind of query option in Octokit - cc @ianhays who tried it recently.

**Comment by karelz** [comment]
@khellang is it actually possible to do the queries via Octokit APIs, or did you just mean using GitHub website?

**Comment by khellang** [comment]
Yep, you can use [the `SearchIssues` method](https://github.com/octokit/octokit.net/blob/master/Octokit/Clients/SearchClient.cs#L52).

**Comment by khellang** [comment]
Here's an example query: https://api.github.com/search/issues?q=org:dotnet%20is:issue%20state:closed%20updated:%3E2017-03-02

**Comment by karelz** [comment]
Great, thanks!

**Comment by karelz** [comment]
Will be superceded by 2.0 version with proper UI for all notifications - see #9.
