### ISSUE TITLE
Enable higher-frequency GitHub data download (avoid API transaction limits)

### ISSUE THREAD

**Issue by karelz** [karelz/GitHubIssues#3]
To enable pulling more data from GitHub (may be required for multi-repo support)

**Comment by karelz** [comment]
We still have the same limits as we used to. It is not enough to download both CoreFX and CoreCLR opened issues. We need OAuth

**Comment by karelz** [comment]
Here's the error I get when I try to cache CoreCLR issues after caching CoreFX issues first:
`Octokit.RateLimitExceededException: API rate limit exceeded for 73.254.202.109. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)`

**Comment by ianhays** [comment]
Are you passing in an authentication token to the cache command e.g. ```cache alerts.xml TOKENNNNNN```? OAuth and auth tokens have the same limit (5000):

https://developer.github.com/v3/#rate-limiting

```
For requests using Basic Authentication or OAuth, you can make up to 5,000 requests per hour. For unauthenticated requests, the rate limit allows you to make up to 60 requests per hour. 
```

**Comment by karelz** [comment]
@ianhays thanks, I missed the token (or forgot). It works!
